apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-voting-app
    name: voting-service
  name: voting-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: demo-voting-app
    name: voting-app-pod
  type: LoadBalancer 
